"""ReAct — interleaving Thought, Action, and Observation.

**What it is.** ReAct ("Reason + Act") prompts the model to alternate
between three roles instead of reasoning in one uninterrupted block:

* **Thought** — a short reasoning step about what to do next.
* **Action** — a structured call to an external tool (search, calculator,
  a database lookup), with explicit arguments.
* **Observation** — the tool's real output, inserted back into the
  transcript (this is *not* generated by the model — it is appended by the
  calling program after actually running the action).

The loop repeats: Thought → Action → Observation → Thought → ... until the
model emits a final answer instead of another action.

**How you build it.**

1. Describe the available tool(s) and the exact ``Action: name[args]``
   syntax the model must use to invoke them.
2. State the task/question.
3. Show one Thought → Action → Observation cycle as a scaffold — the
   Observation is a *placeholder* here (in a real system it is filled in by
   actually executing the action and feeding the result back in the next
   turn).
4. Leave a final "Thought" / "Final Answer" slot so the model knows the
   loop terminates once it has enough information.

**Why grounding via tools helps.** Pure chain-of-thought reasons entirely
from the model's parametric knowledge, which can be stale, incomplete, or
simply wrong (hallucinated facts, outdated numbers). Interleaving real tool
calls grounds each reasoning step in a verifiable observation, so errors
are caught (or corrected) mid-chain instead of compounding silently to the
end.

**Failure modes.**

* **Loops**: the model can repeat the same action expecting a different
  observation, or alternate between two actions indefinitely without
  making progress toward an answer.
* **Hallucinated actions**: the model can emit ``Action: search[...]`` for
  a tool that does not exist, or supply arguments the tool cannot accept —
  the calling program must validate every action before executing it.
* **Ignoring observations**: a model can produce a Thought that
  contradicts the Observation it was just given, effectively discarding the
  grounding the loop was supposed to provide.
* Each cycle costs a full model turn — ReAct is far more expensive in
  latency and tokens than a single CoT completion.
"""

from __future__ import annotations

from optimumai.core.explain import ExplainLevel
from optimumai.core.trace import Trace


def react_trace(
    task: str,
    tool_name: str = "search",
    tool_description: str = "search[query] — looks up query and returns a short snippet.",
) -> Trace:
    """Build a ReAct prompt: tool spec, task, and one Thought/Action/Observation cycle."""
    if not task.strip():
        raise ValueError("task must be a non-empty string")
    if not tool_name.strip():
        raise ValueError("tool_name must be a non-empty string")

    t = Trace(
        op="react",
        formula="prompt = tool_spec ⊕ task ⊕ (Thought → Action → Observation)* ⊕ Final Answer",
        complexity="O(cycles); each cycle is one model turn + one real tool call",
        why_ai=[
            "Grounds reasoning in real, verifiable tool outputs instead of parametric "
            "knowledge alone",
            "Catches errors mid-chain via Observations rather than compounding them silently",
            "Standard scaffold for agents: search, calculators, code execution, DB lookups",
            "Failure modes: repeat-action loops, hallucinated/invalid actions, ignoring "
            "the Observation just returned",
        ],
        meta={"tool_name": tool_name, "tool_description": tool_description},
    )

    t.add(
        "Describe the tool + action syntax",
        f"Tools:\n{tool_description}",
        tool_description,
        detail="Names the exact 'Action: name[args]' syntax the model must emit so the "
        "calling program can parse and validate it before executing anything.",
    )

    t.add(
        "State the task",
        f"Question: {task}",
        task,
    )

    thought_1 = "Thought: I need more information before I can answer."
    action_1 = f"Action: {tool_name}[{task}]"
    observation_1 = "Observation: <result returned by actually running the action above>"
    t.add(
        "Scaffold one Thought -> Action -> Observation cycle",
        f"{thought_1}\n{action_1}\n{observation_1}",
        {"thought": thought_1, "action": action_1, "observation": observation_1},
        detail=(
            "The Observation line is a placeholder in the prompt template — in a real loop "
            "it is produced by the calling program executing the action, not generated by "
            "the model, then appended before the next model turn."
        ),
    )

    final_slot = "Thought: I now have enough information.\nFinal Answer:"
    t.add(
        "Leave a termination slot",
        final_slot,
        final_slot,
        detail="Tells the model how to exit the loop: emit a Final Answer instead of "
        "another Action once the Observations are sufficient.",
    )

    prompt = (
        f"Tools:\n{tool_description}\n\n"
        f"Question: {task}\n\n"
        f"{thought_1}\n{action_1}\n{observation_1}\n\n"
        f"{final_slot}"
    )
    t.add(
        "Assemble the final prompt",
        "prompt = tool spec + question + one demonstrated cycle + termination slot",
        prompt,
    )

    t.result = prompt
    return t


def react(
    task: str,
    tool_name: str = "search",
    tool_description: str = "search[query] — looks up query and returns a short snippet.",
    explain: bool = False,
    level: str | ExplainLevel = ExplainLevel.INTERMEDIATE,
) -> str:
    """Return the assembled ReAct prompt. Set ``explain=True`` to print the trace."""
    t = react_trace(task, tool_name=tool_name, tool_description=tool_description)
    return t.render(level) if explain else t.result


def demo(seed: int = 0) -> Trace:
    """ReAct prompt for a question that needs a search tool to ground the answer."""
    return react_trace(
        task="What is the capital of the country where Mount Kilimanjaro is located?",
        tool_name="search",
        tool_description="search[query] — looks up query and returns a short snippet.",
    )
